# Generated by Django 2.1.3 on 2018-11-17 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailRegis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstNameField', models.CharField(max_length=50, verbose_name='First Name')),
                ('lastNameField', models.CharField(max_length=50, verbose_name='Last Name')),
                ('emailField', models.CharField(max_length=50, verbose_name='E-mail')),
            ],
        ),
    ]
